# Generated by Django 3.0.1 on 2020-07-16 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_fs_searcher', '0002_fileinfo_is_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightroomCatalog',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('hostname', models.CharField(blank=True, max_length=128, verbose_name='hostnames')),
                ('database_file_name', models.CharField(max_length=4096, verbose_name='database_file_name')),
                ('full_database_file_path', models.CharField(max_length=4096, verbose_name='full_database_file_paths')),
                ('is_backup', models.BooleanField(default=False, verbose_name='is_backup')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='django_lr_loader.LightroomCatalog')),
            ],
        ),
        migrations.CreateModel(
            name='LightroomImageFileInfo',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(1, 'File Exists On Hostname'), (2, 'File Exists On Backup'), (3, 'Unknown')], default=3)),
                ('root_id', models.BigIntegerField(verbose_name='root_id')),
                ('folder_id', models.BigIntegerField(verbose_name='folder_id')),
                ('file_id', models.BigIntegerField(verbose_name='file_id')),
                ('root_name', models.CharField(max_length=4096, verbose_name='root_name')),
                ('relative_path', models.CharField(max_length=4096, verbose_name='relative_path')),
                ('root_absolute_path', models.CharField(max_length=4096, verbose_name='root_absolute_path')),
                ('file_original_name', models.CharField(max_length=4096, verbose_name='file_original_name')),
                ('root_rel_path_from_catalog', models.CharField(max_length=4096, verbose_name='root_rel_path_from_catalog')),
                ('file_base_name', models.CharField(max_length=4096, verbose_name='file_base_name')),
                ('file_extension', models.CharField(max_length=4096, verbose_name='file_extension')),
                ('print_path', models.CharField(max_length=4096, verbose_name='print_path')),
                ('lightroom_catalog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_lr_loader.LightroomCatalog', verbose_name='lightroom_catalog')),
            ],
        ),
        migrations.CreateModel(
            name='ImageToFileInfo',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('certainty', models.IntegerField(default=0, verbose_name='certainty')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_fs_searcher.FileInfo', verbose_name='file_info')),
                ('lightroom_catalog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_lr_loader.LightroomCatalog', verbose_name='lightroom_catalog')),
                ('lightroom_image_file_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_lr_loader.LightroomImageFileInfo', verbose_name='lightroom_image_file_info')),
            ],
        ),
    ]
